name: Unit Testing and Linting


# Unit testing and linting is run on push and pull request to main and dev branches
on:
  push:
    branches:
      - main
      - dev
      - feature-**
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    #defining runner parameters
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8] # development in 3.8 but can be tested for multiple versions simultaneity

    # defining PYTHONPATH env var for pylint and flake8 - fixes module location fault in GitHub runners
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements/requirements.txt
        python -m spacy download en_core_web_lg
    - name: Lint with Flake8
      run: |
        # based on GitHub pre-made flake8 python app workflow 
        echo ${{ env.PYTHONPATH }}
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --statistics

    - name: Run Tests with pytest
      run: |
        echo ${{ env.PYTHONPATH }}
        pytest

    - name: Test Coverage
      run: |
        coverage run -m pytest
        coverage report -m 

